package org.likide.bbgraph.init.model;
// Generated 12 avr. 2020 22:05:12 by Hibernate Tools 5.4.13.Final



/**
 * GraphArchivedgraph generated by hbm2java
 */
public class GraphArchivedgraph  implements java.io.Serializable {


     private int id;
     private int version;
     private int graphId;
     private String name;
     private String jps;
     private int template;
     private String savedOn;

    public GraphArchivedgraph() {
    }

    public GraphArchivedgraph(int id, int graphId, String name, String jps, int template, String savedOn) {
       this.id = id;
       this.graphId = graphId;
       this.name = name;
       this.jps = jps;
       this.template = template;
       this.savedOn = savedOn;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public int getGraphId() {
        return this.graphId;
    }
    
    public void setGraphId(int graphId) {
        this.graphId = graphId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getJps() {
        return this.jps;
    }
    
    public void setJps(String jps) {
        this.jps = jps;
    }
    public int getTemplate() {
        return this.template;
    }
    
    public void setTemplate(int template) {
        this.template = template;
    }
    public String getSavedOn() {
        return this.savedOn;
    }
    
    public void setSavedOn(String savedOn) {
        this.savedOn = savedOn;
    }




}


